### ISSUE TITLE
donation project to the nebula-contrib tent/org

### ISSUE THREAD

**Issue by wey-gu** [nebula-contrib/zio-nebula#1]
Dear @jxnu-liguobin /HJ Fruit

ZIO-Nebula is a Great/Decent project, thanks a lot for the creation!

If it's possible to move this project to Nebula-Contrib Tent, as discussed [here](https://github.com/vesoft-inc/nebula-java/issues/540), our org admin @Shinji-IkariG could help with that!

Thanks!

**Comment by wey-gu** [comment]
I think the first move is to transfer the repo to @Shinji-IkariG and in parallel, @QingZ11 will reach out to you via mail(the outlook dot com one in your profile)!

Thanks!

**Comment by wey-gu** [comment]
Dear @jxnu-liguobin , could we transfer this repo to @Shinji-IkariG first, then he will put the repo to the Org afterward.

Thanks!

**Comment by jxnu-liguobin** [comment]
> 

Waiting for acceptance

**Comment by jxnu-liguobin** [comment]
There is some work to be done.

This project uses the popular tool `sbt-ci-release` to automatically publish artifacts, so it needs to rely on these variables. (If we change the publishing organization). 

If there is no need to change the organization of the artifact, are there variables present after the repository transfer?
![image](https://github.com/nebula-contrib/zio-nebula/assets/29496873/3d7e552c-3ed7-4015-9d3b-1c43027a8eec)

**Comment by wey-gu** [comment]
> There is some work to be done.
> 
> This project uses the popular tool `sbt-ci-release` to automatically publish artifacts, so it needs to rely on these variables. (If we change the publishing organization).
> 
> If there is no need to change the organization of the artifact, are there variables present after the repository transfer? ![image](https://user-images.githubusercontent.com/29496873/266194756-3d7e552c-3ed7-4015-9d3b-1c43027a8eec.png)

What is your preference? I think we could keep the existing Sonatype publishing repo, but change the variables with a prefix, and you hand over the credentials to @Shinji-IkariG so he could configure them as secrets.

Or we could apply for its Sonatype under nebula-contrib.org.

**Comment by wey-gu** [comment]
Wow it's already under new org! 🎉

**Comment by wey-gu** [comment]
confirmed with @jxnu-liguobin offline to know that the publishing with sbt is verified to be done smoothly already within the current configuration.
